[phases.setup]
nixPkgs = ["nodejs_22"]

[phases.install]
cmds = ["cd oranje && npm install --legacy-peer-deps"]

[phases.build]
cmds = ["cd oranje && npm run build"]

[start]
cmd = "cd oranje && npm start"
